version: "3"

services:
  traefik:
    image: traefik:latest
    command:
      - --api.insecure=true
      - --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  whoami:
    image:
      containous/whoami
    labels:
      - traefik.http.routers.whoami.rule=Host(`app.test`)
